// This file is @generated by prost-build.
pub mod envoy {
    pub mod extensions {
        pub mod rate_limit_descriptors {
            pub mod expr {
                pub mod v3 {
                    include!("envoy.extensions.rate_limit_descriptors.expr.v3.rs");
                }
            }
        }
    }
}
pub mod google {
    pub mod api {
        pub mod expr {
            pub mod v1alpha1 {
                include!("google.api.expr.v1alpha1.rs");
            }
        }
    }
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
pub mod validate {
    include!("validate.rs");
}
