// This file is @generated by prost-build.
pub mod envoy {
    pub mod extensions {
        pub mod health_check {
            pub mod event_sinks {
                pub mod file {
                    pub mod v3 {
                        include!("envoy.extensions.health_check.event_sinks.file.v3.rs");
                    }
                }
            }
        }
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
pub mod validate {
    include!("validate.rs");
}
