// This file is @generated by prost-build.
pub mod envoy {
    pub mod extensions {
        pub mod transport_sockets {
            pub mod raw_buffer {
                pub mod v3 {
                    include!("envoy.extensions.transport_sockets.raw_buffer.v3.rs");
                }
            }
        }
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
