// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CdnLoopConfig {
    #[prost(string, tag = "1")]
    pub cdn_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub max_allowed_occurrences: u32,
}
