// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpstreamLocalityStats {
    #[prost(message, optional, tag = "1")]
    pub locality: ::core::option::Option<super::super::core::v3::Locality>,
    #[prost(uint64, tag = "2")]
    pub total_successful_requests: u64,
    #[prost(uint64, tag = "3")]
    pub total_requests_in_progress: u64,
    #[prost(uint64, tag = "4")]
    pub total_error_requests: u64,
    #[prost(uint64, tag = "8")]
    pub total_issued_requests: u64,
    #[prost(uint64, tag = "9")]
    pub total_active_connections: u64,
    #[prost(uint64, tag = "10")]
    pub total_new_connections: u64,
    #[prost(uint64, tag = "11")]
    pub total_fail_connections: u64,
    #[prost(message, optional, tag = "12")]
    pub cpu_utilization: ::core::option::Option<UnnamedEndpointLoadMetricStats>,
    #[prost(message, optional, tag = "13")]
    pub mem_utilization: ::core::option::Option<UnnamedEndpointLoadMetricStats>,
    #[prost(message, optional, tag = "14")]
    pub application_utilization: ::core::option::Option<UnnamedEndpointLoadMetricStats>,
    #[prost(message, repeated, tag = "5")]
    pub load_metric_stats: ::prost::alloc::vec::Vec<EndpointLoadMetricStats>,
    #[prost(message, repeated, tag = "7")]
    pub upstream_endpoint_stats: ::prost::alloc::vec::Vec<UpstreamEndpointStats>,
    #[prost(uint32, tag = "6")]
    pub priority: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpstreamEndpointStats {
    #[prost(message, optional, tag = "1")]
    pub address: ::core::option::Option<super::super::core::v3::Address>,
    #[prost(message, optional, tag = "6")]
    pub metadata: ::core::option::Option<
        super::super::super::super::google::protobuf::Struct,
    >,
    #[prost(uint64, tag = "2")]
    pub total_successful_requests: u64,
    #[prost(uint64, tag = "3")]
    pub total_requests_in_progress: u64,
    #[prost(uint64, tag = "4")]
    pub total_error_requests: u64,
    #[prost(uint64, tag = "7")]
    pub total_issued_requests: u64,
    #[prost(message, repeated, tag = "5")]
    pub load_metric_stats: ::prost::alloc::vec::Vec<EndpointLoadMetricStats>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EndpointLoadMetricStats {
    #[prost(string, tag = "1")]
    pub metric_name: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub num_requests_finished_with_metric: u64,
    #[prost(double, tag = "3")]
    pub total_metric_value: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UnnamedEndpointLoadMetricStats {
    #[prost(uint64, tag = "1")]
    pub num_requests_finished_with_metric: u64,
    #[prost(double, tag = "2")]
    pub total_metric_value: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClusterStats {
    #[prost(string, tag = "1")]
    pub cluster_name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub cluster_service_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub upstream_locality_stats: ::prost::alloc::vec::Vec<UpstreamLocalityStats>,
    #[prost(uint64, tag = "3")]
    pub total_dropped_requests: u64,
    #[prost(message, repeated, tag = "5")]
    pub dropped_requests: ::prost::alloc::vec::Vec<cluster_stats::DroppedRequests>,
    #[prost(message, optional, tag = "4")]
    pub load_report_interval: ::core::option::Option<
        super::super::super::super::google::protobuf::Duration,
    >,
}
/// Nested message and enum types in `ClusterStats`.
pub mod cluster_stats {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct DroppedRequests {
        #[prost(string, tag = "1")]
        pub category: ::prost::alloc::string::String,
        #[prost(uint64, tag = "2")]
        pub dropped_count: u64,
    }
}
