// This file is @generated by prost-build.
pub mod envoy {
    pub mod api {
        pub mod v2 {
            include!("envoy.api.v2.rs");
            pub mod auth {
                include!("envoy.api.v2.auth.rs");
            }
            pub mod cluster {
                include!("envoy.api.v2.cluster.rs");
            }
            pub mod core {
                include!("envoy.api.v2.core.rs");
            }
            pub mod endpoint {
                include!("envoy.api.v2.endpoint.rs");
            }
            pub mod listener {
                include!("envoy.api.v2.listener.rs");
            }
            pub mod route {
                include!("envoy.api.v2.route.rs");
            }
        }
    }
    pub mod config {
        pub mod bootstrap {
            pub mod v2 {
                include!("envoy.config.bootstrap.v2.rs");
            }
        }
        pub mod filter {
            pub mod accesslog {
                pub mod v2 {
                    include!("envoy.config.filter.accesslog.v2.rs");
                }
            }
        }
        pub mod listener {
            pub mod v2 {
                include!("envoy.config.listener.v2.rs");
            }
        }
        pub mod metrics {
            pub mod v2 {
                include!("envoy.config.metrics.v2.rs");
            }
        }
        pub mod overload {
            pub mod v2alpha {
                include!("envoy.config.overload.v2alpha.rs");
            }
        }
        pub mod trace {
            pub mod v2 {
                include!("envoy.config.trace.v2.rs");
            }
        }
    }
    pub mod r#type {
        include!("envoy.r#type.rs");
        pub mod matcher {
            include!("envoy.r#type.matcher.rs");
        }
        pub mod metadata {
            pub mod v2 {
                include!("envoy.r#type.metadata.v2.rs");
            }
        }
        pub mod tracing {
            pub mod v2 {
                include!("envoy.r#type.tracing.v2.rs");
            }
        }
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
pub mod validate {
    include!("validate.rs");
}
