// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FilterConfig {
    #[prost(bool, tag = "1")]
    pub emit_filter_state: bool,
    #[prost(oneof = "filter_config::PerMethodStatSpecifier", tags = "2, 3")]
    pub per_method_stat_specifier: ::core::option::Option<
        filter_config::PerMethodStatSpecifier,
    >,
}
/// Nested message and enum types in `FilterConfig`.
pub mod filter_config {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum PerMethodStatSpecifier {
        #[prost(message, tag = "2")]
        IndividualMethodStatsAllowlist(
            super::super::super::super::super::super::api::v2::core::GrpcMethodList,
        ),
        #[prost(message, tag = "3")]
        StatsForAllMethods(
            super::super::super::super::super::super::super::google::protobuf::BoolValue,
        ),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FilterObject {
    #[prost(uint64, tag = "1")]
    pub request_message_count: u64,
    #[prost(uint64, tag = "2")]
    pub response_message_count: u64,
}
