// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SinkConfig {
    #[prost(bool, tag = "2")]
    pub report_counters_as_deltas: bool,
    #[prost(bool, tag = "3")]
    pub report_histograms_as_deltas: bool,
    #[prost(message, optional, tag = "4")]
    pub emit_tags_as_attributes: ::core::option::Option<
        super::super::super::super::super::google::protobuf::BoolValue,
    >,
    #[prost(message, optional, tag = "5")]
    pub use_tag_extracted_name: ::core::option::Option<
        super::super::super::super::super::google::protobuf::BoolValue,
    >,
    #[prost(string, tag = "6")]
    pub prefix: ::prost::alloc::string::String,
    #[prost(oneof = "sink_config::ProtocolSpecifier", tags = "1")]
    pub protocol_specifier: ::core::option::Option<sink_config::ProtocolSpecifier>,
}
/// Nested message and enum types in `SinkConfig`.
pub mod sink_config {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ProtocolSpecifier {
        #[prost(message, tag = "1")]
        GrpcService(super::super::super::super::super::config::core::v3::GrpcService),
    }
}
