// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyValueStoreConfig {
    #[prost(message, optional, tag = "1")]
    pub config: ::core::option::Option<
        super::super::super::core::v3::TypedExtensionConfig,
    >,
}
