// This file is @generated by prost-build.
pub mod envoy {
    pub mod annotations {
        include!("envoy.annotations.rs");
    }
    pub mod config {
        pub mod core {
            pub mod v3 {
                include!("envoy.config.core.v3.rs");
            }
        }
    }
    pub mod r#type {
        pub mod v3 {
            include!("envoy.r#type.v3.rs");
        }
    }
    pub mod service {
        pub mod discovery {
            pub mod v3 {
                include!("envoy.service.discovery.v3.rs");
            }
        }
        pub mod secret {
            pub mod v3 {
                include!("envoy.service.secret.v3.rs");
            }
        }
    }
}
pub mod google {
    pub mod api {
        include!("google.api.rs");
    }
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
    pub mod rpc {
        include!("google.rpc.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
pub mod validate {
    include!("validate.rs");
}
pub mod xds {
    pub mod annotations {
        pub mod v3 {
            include!("xds.annotations.v3.rs");
        }
    }
    pub mod core {
        pub mod v3 {
            include!("xds.core.v3.rs");
        }
    }
}
