// This file is @generated by prost-build.
pub mod envoy {
    pub mod api {
        pub mod v2 {
            pub mod core {
                include!("envoy.api.v2.core.rs");
            }
        }
    }
    pub mod data {
        pub mod core {
            pub mod v2alpha {
                include!("envoy.data.core.v2alpha.rs");
            }
        }
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
pub mod validate {
    include!("validate.rs");
}
