// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tap {
    #[prost(message, optional, tag = "1")]
    pub common_config: ::core::option::Option<
        super::super::super::super::common::tap::v3::CommonExtensionConfig,
    >,
    #[prost(bool, tag = "2")]
    pub record_headers_received_time: bool,
    #[prost(bool, tag = "3")]
    pub record_downstream_connection: bool,
}
