// This file is @generated by prost-build.
pub mod envoy {
    pub mod config {
        pub mod retry {
            pub mod previous_priorities {
                include!("envoy.config.retry.previous_priorities.rs");
            }
        }
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
pub mod validate {
    include!("validate.rs");
}
