// This file is @generated by prost-build.
pub mod envoy {
    pub mod extensions {
        pub mod udp_packet_writer {
            pub mod v3 {
                include!("envoy.extensions.udp_packet_writer.v3.rs");
            }
        }
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
