// This file is @generated by prost-build.
pub mod envoy {
    pub mod r#type {
        include!("envoy.r#type.rs");
        pub mod matcher {
            include!("envoy.r#type.matcher.rs");
        }
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
pub mod validate {
    include!("validate.rs");
}
