// This file is @generated by prost-build.
pub mod envoy {
    pub mod extensions {
        pub mod quic {
            pub mod proof_source {
                pub mod v3 {
                    include!("envoy.extensions.quic.proof_source.v3.rs");
                }
            }
        }
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
