// This file is @generated by prost-build.
pub mod envoy {
    pub mod config {
        pub mod cluster {
            pub mod v3 {
                include!("envoy.config.cluster.v3.rs");
            }
        }
        pub mod core {
            pub mod v3 {
                include!("envoy.config.core.v3.rs");
            }
        }
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
pub mod validate {
    include!("validate.rs");
}
