// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExtAuthz {
    #[prost(string, tag = "1")]
    pub stat_prefix: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub grpc_service: ::core::option::Option<
        super::super::super::super::super::api::v2::core::GrpcService,
    >,
    #[prost(bool, tag = "3")]
    pub failure_mode_allow: bool,
    #[prost(bool, tag = "4")]
    pub include_peer_certificate: bool,
}
