// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Router {
    #[prost(message, optional, tag = "1")]
    pub dynamic_stats: ::core::option::Option<
        super::super::super::super::super::super::google::protobuf::BoolValue,
    >,
    #[prost(bool, tag = "2")]
    pub start_child_span: bool,
    #[prost(message, repeated, tag = "3")]
    pub upstream_log: ::prost::alloc::vec::Vec<
        super::super::super::accesslog::v2::AccessLog,
    >,
    #[prost(bool, tag = "4")]
    pub suppress_envoy_headers: bool,
    #[prost(string, repeated, tag = "5")]
    pub strict_check_headers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "6")]
    pub respect_expected_rq_timeout: bool,
}
