// This file is @generated by prost-build.
pub mod envoy {
    pub mod extensions {
        pub mod load_balancing_policies {
            pub mod pick_first {
                pub mod v3 {
                    include!("envoy.extensions.load_balancing_policies.pick_first.v3.rs");
                }
            }
        }
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
