// This file is @generated by prost-build.
pub mod envoy {
    pub mod config {
        pub mod health_checker {
            pub mod redis {
                pub mod v2 {
                    include!("envoy.config.health_checker.redis.v2.rs");
                }
            }
        }
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
