// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RateLimitQuotaUsageReports {
    #[prost(string, tag = "1")]
    pub domain: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub bucket_quota_usages: ::prost::alloc::vec::Vec<
        rate_limit_quota_usage_reports::BucketQuotaUsage,
    >,
}
/// Nested message and enum types in `RateLimitQuotaUsageReports`.
pub mod rate_limit_quota_usage_reports {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct BucketQuotaUsage {
        #[prost(message, optional, tag = "1")]
        pub bucket_id: ::core::option::Option<super::BucketId>,
        #[prost(message, optional, tag = "2")]
        pub time_elapsed: ::core::option::Option<
            super::super::super::super::super::google::protobuf::Duration,
        >,
        #[prost(uint64, tag = "3")]
        pub num_requests_allowed: u64,
        #[prost(uint64, tag = "4")]
        pub num_requests_denied: u64,
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RateLimitQuotaResponse {
    #[prost(message, repeated, tag = "1")]
    pub bucket_action: ::prost::alloc::vec::Vec<rate_limit_quota_response::BucketAction>,
}
/// Nested message and enum types in `RateLimitQuotaResponse`.
pub mod rate_limit_quota_response {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct BucketAction {
        #[prost(message, optional, tag = "1")]
        pub bucket_id: ::core::option::Option<super::BucketId>,
        #[prost(oneof = "bucket_action::BucketAction", tags = "2, 3")]
        pub bucket_action: ::core::option::Option<bucket_action::BucketAction>,
    }
    /// Nested message and enum types in `BucketAction`.
    pub mod bucket_action {
        #[allow(clippy::derive_partial_eq_without_eq)]
        #[derive(Clone, Copy, PartialEq, ::prost::Message)]
        pub struct QuotaAssignmentAction {
            #[prost(message, optional, tag = "2")]
            pub assignment_time_to_live: ::core::option::Option<
                super::super::super::super::super::super::google::protobuf::Duration,
            >,
            #[prost(message, optional, tag = "3")]
            pub rate_limit_strategy: ::core::option::Option<
                super::super::super::super::super::r#type::v3::RateLimitStrategy,
            >,
        }
        #[allow(clippy::derive_partial_eq_without_eq)]
        #[derive(Clone, Copy, PartialEq, ::prost::Message)]
        pub struct AbandonAction {}
        #[allow(clippy::derive_partial_eq_without_eq)]
        #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
        pub enum BucketAction {
            #[prost(message, tag = "2")]
            QuotaAssignmentAction(QuotaAssignmentAction),
            #[prost(message, tag = "3")]
            AbandonAction(AbandonAction),
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BucketId {
    #[prost(map = "string, string", tag = "1")]
    pub bucket: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Generated client implementations.
pub mod rate_limit_quota_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Defines the Rate Limit Quota Service (RLQS).
    #[derive(Debug, Clone)]
    pub struct RateLimitQuotaServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl RateLimitQuotaServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> RateLimitQuotaServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> RateLimitQuotaServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            RateLimitQuotaServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Main communication channel: the data plane sends usage reports to the RLQS server,
        /// and the server asynchronously responding with the assignments.
        pub async fn stream_rate_limit_quotas(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::RateLimitQuotaUsageReports,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::RateLimitQuotaResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/envoy.service.rate_limit_quota.v3.RateLimitQuotaService/StreamRateLimitQuotas",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "envoy.service.rate_limit_quota.v3.RateLimitQuotaService",
                        "StreamRateLimitQuotas",
                    ),
                );
            self.inner.streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod rate_limit_quota_service_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with RateLimitQuotaServiceServer.
    #[async_trait]
    pub trait RateLimitQuotaService: Send + Sync + 'static {
        /// Server streaming response type for the StreamRateLimitQuotas method.
        type StreamRateLimitQuotasStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::RateLimitQuotaResponse, tonic::Status>,
            >
            + Send
            + 'static;
        /// Main communication channel: the data plane sends usage reports to the RLQS server,
        /// and the server asynchronously responding with the assignments.
        async fn stream_rate_limit_quotas(
            &self,
            request: tonic::Request<tonic::Streaming<super::RateLimitQuotaUsageReports>>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamRateLimitQuotasStream>,
            tonic::Status,
        >;
    }
    /// Defines the Rate Limit Quota Service (RLQS).
    #[derive(Debug)]
    pub struct RateLimitQuotaServiceServer<T: RateLimitQuotaService> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T: RateLimitQuotaService> RateLimitQuotaServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for RateLimitQuotaServiceServer<T>
    where
        T: RateLimitQuotaService,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/envoy.service.rate_limit_quota.v3.RateLimitQuotaService/StreamRateLimitQuotas" => {
                    #[allow(non_camel_case_types)]
                    struct StreamRateLimitQuotasSvc<T: RateLimitQuotaService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: RateLimitQuotaService,
                    > tonic::server::StreamingService<super::RateLimitQuotaUsageReports>
                    for StreamRateLimitQuotasSvc<T> {
                        type Response = super::RateLimitQuotaResponse;
                        type ResponseStream = T::StreamRateLimitQuotasStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::RateLimitQuotaUsageReports>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RateLimitQuotaService>::stream_rate_limit_quotas(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamRateLimitQuotasSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", tonic::Code::Unimplemented as i32)
                                .header(
                                    http::header::CONTENT_TYPE,
                                    tonic::metadata::GRPC_CONTENT_TYPE,
                                )
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: RateLimitQuotaService> Clone for RateLimitQuotaServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: RateLimitQuotaService> tonic::server::NamedService
    for RateLimitQuotaServiceServer<T> {
        const NAME: &'static str = "envoy.service.rate_limit_quota.v3.RateLimitQuotaService";
    }
}
