// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Cors {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CorsPolicy {
    #[prost(message, repeated, tag = "1")]
    pub allow_origin_string_match: ::prost::alloc::vec::Vec<
        super::super::super::super::super::r#type::matcher::v3::StringMatcher,
    >,
    #[prost(string, tag = "2")]
    pub allow_methods: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub allow_headers: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub expose_headers: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub max_age: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "6")]
    pub allow_credentials: ::core::option::Option<
        super::super::super::super::super::super::google::protobuf::BoolValue,
    >,
    #[prost(message, optional, tag = "7")]
    pub filter_enabled: ::core::option::Option<
        super::super::super::super::super::config::core::v3::RuntimeFractionalPercent,
    >,
    #[prost(message, optional, tag = "8")]
    pub shadow_enabled: ::core::option::Option<
        super::super::super::super::super::config::core::v3::RuntimeFractionalPercent,
    >,
    #[prost(message, optional, tag = "9")]
    pub allow_private_network_access: ::core::option::Option<
        super::super::super::super::super::super::google::protobuf::BoolValue,
    >,
    #[prost(message, optional, tag = "10")]
    pub forward_not_matching_preflights: ::core::option::Option<
        super::super::super::super::super::super::google::protobuf::BoolValue,
    >,
}
