// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GrpcJsonTranscoder {
    #[prost(string, repeated, tag = "2")]
    pub services: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "3")]
    pub print_options: ::core::option::Option<grpc_json_transcoder::PrintOptions>,
    #[prost(bool, tag = "5")]
    pub match_incoming_request_route: bool,
    #[prost(string, repeated, tag = "6")]
    pub ignored_query_parameters: ::prost::alloc::vec::Vec<
        ::prost::alloc::string::String,
    >,
    #[prost(bool, tag = "7")]
    pub auto_mapping: bool,
    #[prost(bool, tag = "8")]
    pub ignore_unknown_query_parameters: bool,
    #[prost(bool, tag = "9")]
    pub convert_grpc_status: bool,
    #[prost(oneof = "grpc_json_transcoder::DescriptorSet", tags = "1, 4")]
    pub descriptor_set: ::core::option::Option<grpc_json_transcoder::DescriptorSet>,
}
/// Nested message and enum types in `GrpcJsonTranscoder`.
pub mod grpc_json_transcoder {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct PrintOptions {
        #[prost(bool, tag = "1")]
        pub add_whitespace: bool,
        #[prost(bool, tag = "2")]
        pub always_print_primitive_fields: bool,
        #[prost(bool, tag = "3")]
        pub always_print_enums_as_ints: bool,
        #[prost(bool, tag = "4")]
        pub preserve_proto_field_names: bool,
    }
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum DescriptorSet {
        #[prost(string, tag = "1")]
        ProtoDescriptor(::prost::alloc::string::String),
        #[prost(bytes, tag = "4")]
        ProtoDescriptorBin(::prost::alloc::vec::Vec<u8>),
    }
}
