// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FaultAbort {
    #[prost(message, optional, tag = "3")]
    pub percentage: ::core::option::Option<
        super::super::super::super::super::r#type::FractionalPercent,
    >,
    #[prost(oneof = "fault_abort::ErrorType", tags = "2, 4")]
    pub error_type: ::core::option::Option<fault_abort::ErrorType>,
}
/// Nested message and enum types in `FaultAbort`.
pub mod fault_abort {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct HeaderAbort {}
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum ErrorType {
        #[prost(uint32, tag = "2")]
        HttpStatus(u32),
        #[prost(message, tag = "4")]
        HeaderAbort(HeaderAbort),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpFault {
    #[prost(message, optional, tag = "1")]
    pub delay: ::core::option::Option<super::super::super::fault::v2::FaultDelay>,
    #[prost(message, optional, tag = "2")]
    pub abort: ::core::option::Option<FaultAbort>,
    #[prost(string, tag = "3")]
    pub upstream_cluster: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub headers: ::prost::alloc::vec::Vec<
        super::super::super::super::super::api::v2::route::HeaderMatcher,
    >,
    #[prost(string, repeated, tag = "5")]
    pub downstream_nodes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "6")]
    pub max_active_faults: ::core::option::Option<
        super::super::super::super::super::super::google::protobuf::UInt32Value,
    >,
    #[prost(message, optional, tag = "7")]
    pub response_rate_limit: ::core::option::Option<
        super::super::super::fault::v2::FaultRateLimit,
    >,
    #[prost(string, tag = "8")]
    pub delay_percent_runtime: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub abort_percent_runtime: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub delay_duration_runtime: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub abort_http_status_runtime: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub max_active_faults_runtime: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub response_rate_limit_percent_runtime: ::prost::alloc::string::String,
}
