// This file is @generated by prost-build.
pub mod envoy {
    pub mod api {
        pub mod v2 {
            include!("envoy.api.v2.rs");
            pub mod auth {
                include!("envoy.api.v2.auth.rs");
            }
            pub mod cluster {
                include!("envoy.api.v2.cluster.rs");
            }
            pub mod core {
                include!("envoy.api.v2.core.rs");
            }
            pub mod endpoint {
                include!("envoy.api.v2.endpoint.rs");
            }
        }
    }
    pub mod config {
        pub mod common {
            pub mod dynamic_forward_proxy {
                pub mod v2alpha {
                    include!("envoy.config.common.dynamic_forward_proxy.v2alpha.rs");
                }
            }
        }
        pub mod filter {
            pub mod http {
                pub mod dynamic_forward_proxy {
                    pub mod v2alpha {
                        include!("envoy.config.filter.http.dynamic_forward_proxy.v2alpha.rs");
                    }
                }
            }
        }
    }
    pub mod r#type {
        include!("envoy.r#type.rs");
        pub mod matcher {
            include!("envoy.r#type.matcher.rs");
        }
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
pub mod validate {
    include!("validate.rs");
}
