// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InjectedResourceConfig {
    #[prost(string, tag = "1")]
    pub filename: ::prost::alloc::string::String,
}
