// This file is @generated by prost-build.
pub mod envoy {
    pub mod extensions {
        pub mod http {
            pub mod stateful_session {
                pub mod header {
                    pub mod v3 {
                        include!("envoy.extensions.http.stateful_session.header.v3.rs");
                    }
                }
            }
        }
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
pub mod validate {
    include!("validate.rs");
}
