// This file is @generated by prost-build.
pub mod envoy {
    pub mod extensions {
        pub mod health_checkers {
            pub mod redis {
                pub mod v3 {
                    include!("envoy.extensions.health_checkers.redis.v3.rs");
                }
            }
        }
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
