// This file is @generated by prost-build.
pub mod envoy {
    pub mod config {
        pub mod filter {
            pub mod fault {
                pub mod v2 {
                    include!("envoy.config.filter.fault.v2.rs");
                }
            }
            pub mod network {
                pub mod mongo_proxy {
                    pub mod v2 {
                        include!("envoy.config.filter.network.mongo_proxy.v2.rs");
                    }
                }
            }
        }
    }
    pub mod r#type {
        include!("envoy.r#type.rs");
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
pub mod validate {
    include!("validate.rs");
}
