// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommonExtensionConfig {
    #[prost(oneof = "common_extension_config::ConfigType", tags = "1, 2")]
    pub config_type: ::core::option::Option<common_extension_config::ConfigType>,
}
/// Nested message and enum types in `CommonExtensionConfig`.
pub mod common_extension_config {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ConfigType {
        #[prost(message, tag = "1")]
        AdminConfig(super::AdminConfig),
        #[prost(message, tag = "2")]
        StaticConfig(
            super::super::super::super::super::service::tap::v2alpha::TapConfig,
        ),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AdminConfig {
    #[prost(string, tag = "1")]
    pub config_id: ::prost::alloc::string::String,
}
