// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tap {
    #[prost(message, optional, tag = "1")]
    pub common_config: ::core::option::Option<
        super::super::super::common::tap::v2alpha::CommonExtensionConfig,
    >,
    #[prost(message, optional, tag = "2")]
    pub transport_socket: ::core::option::Option<
        super::super::super::super::api::v2::core::TransportSocket,
    >,
}
