// This file is @generated by prost-build.
pub mod envoy {
    pub mod extensions {
        pub mod matching {
            pub mod input_matchers {
                pub mod consistent_hashing {
                    pub mod v3 {
                        include!("envoy.extensions.matching.input_matchers.consistent_hashing.v3.rs");
                    }
                }
            }
        }
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
pub mod validate {
    include!("validate.rs");
}
