// This file is @generated by prost-build.
pub mod envoy {
    pub mod data {
        pub mod core {
            pub mod v3 {
                include!("envoy.data.core.v3.rs");
            }
        }
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
