// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JwtProvider {
    #[prost(string, tag = "1")]
    pub issuer: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub audiences: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "5")]
    pub forward: bool,
    #[prost(message, repeated, tag = "6")]
    pub from_headers: ::prost::alloc::vec::Vec<JwtHeader>,
    #[prost(string, repeated, tag = "7")]
    pub from_params: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "8")]
    pub forward_payload_header: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub payload_in_metadata: ::prost::alloc::string::String,
    #[prost(oneof = "jwt_provider::JwksSourceSpecifier", tags = "3, 4")]
    pub jwks_source_specifier: ::core::option::Option<jwt_provider::JwksSourceSpecifier>,
}
/// Nested message and enum types in `JwtProvider`.
pub mod jwt_provider {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum JwksSourceSpecifier {
        #[prost(message, tag = "3")]
        RemoteJwks(super::RemoteJwks),
        #[prost(message, tag = "4")]
        LocalJwks(super::super::super::super::super::super::api::v2::core::DataSource),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoteJwks {
    #[prost(message, optional, tag = "1")]
    pub http_uri: ::core::option::Option<
        super::super::super::super::super::api::v2::core::HttpUri,
    >,
    #[prost(message, optional, tag = "2")]
    pub cache_duration: ::core::option::Option<
        super::super::super::super::super::super::google::protobuf::Duration,
    >,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JwtHeader {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value_prefix: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProviderWithAudiences {
    #[prost(string, tag = "1")]
    pub provider_name: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub audiences: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JwtRequirement {
    #[prost(oneof = "jwt_requirement::RequiresType", tags = "1, 2, 3, 4, 5, 6")]
    pub requires_type: ::core::option::Option<jwt_requirement::RequiresType>,
}
/// Nested message and enum types in `JwtRequirement`.
pub mod jwt_requirement {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum RequiresType {
        #[prost(string, tag = "1")]
        ProviderName(::prost::alloc::string::String),
        #[prost(message, tag = "2")]
        ProviderAndAudiences(super::ProviderWithAudiences),
        #[prost(message, tag = "3")]
        RequiresAny(super::JwtRequirementOrList),
        #[prost(message, tag = "4")]
        RequiresAll(super::JwtRequirementAndList),
        #[prost(message, tag = "5")]
        AllowMissingOrFailed(
            super::super::super::super::super::super::super::google::protobuf::Empty,
        ),
        #[prost(message, tag = "6")]
        AllowMissing(
            super::super::super::super::super::super::super::google::protobuf::Empty,
        ),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JwtRequirementOrList {
    #[prost(message, repeated, tag = "1")]
    pub requirements: ::prost::alloc::vec::Vec<JwtRequirement>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JwtRequirementAndList {
    #[prost(message, repeated, tag = "1")]
    pub requirements: ::prost::alloc::vec::Vec<JwtRequirement>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequirementRule {
    #[prost(message, optional, tag = "1")]
    pub r#match: ::core::option::Option<
        super::super::super::super::super::api::v2::route::RouteMatch,
    >,
    #[prost(message, optional, tag = "2")]
    pub requires: ::core::option::Option<JwtRequirement>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FilterStateRule {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(map = "string, message", tag = "3")]
    pub requires: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        JwtRequirement,
    >,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JwtAuthentication {
    #[prost(map = "string, message", tag = "1")]
    pub providers: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        JwtProvider,
    >,
    #[prost(message, repeated, tag = "2")]
    pub rules: ::prost::alloc::vec::Vec<RequirementRule>,
    #[prost(message, optional, tag = "3")]
    pub filter_state_rules: ::core::option::Option<FilterStateRule>,
    #[prost(bool, tag = "4")]
    pub bypass_cors_preflight: bool,
}
