// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DynatraceSamplerConfig {
    #[prost(string, tag = "1")]
    pub tenant: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub cluster_id: i32,
    #[prost(message, optional, tag = "3")]
    pub http_service: ::core::option::Option<
        super::super::super::super::super::config::core::v3::HttpService,
    >,
    #[prost(uint32, tag = "4")]
    pub root_spans_per_minute: u32,
}
