// This file is @generated by prost-build.
pub mod envoy {
    pub mod extensions {
        pub mod key_value {
            pub mod file_based {
                pub mod v3 {
                    include!("envoy.extensions.key_value.file_based.v3.rs");
                }
            }
        }
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
pub mod validate {
    include!("validate.rs");
}
pub mod xds {
    pub mod annotations {
        pub mod v3 {
            include!("xds.annotations.v3.rs");
        }
    }
}
