// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExtensionWithMatcher {
    #[deprecated]
    #[prost(message, optional, tag = "1")]
    pub matcher: ::core::option::Option<
        super::super::super::super::config::common::matcher::v3::Matcher,
    >,
    #[prost(message, optional, tag = "3")]
    pub xds_matcher: ::core::option::Option<
        super::super::super::super::super::xds::r#type::matcher::v3::Matcher,
    >,
    #[prost(message, optional, tag = "2")]
    pub extension_config: ::core::option::Option<
        super::super::super::super::config::core::v3::TypedExtensionConfig,
    >,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExtensionWithMatcherPerRoute {
    #[prost(message, optional, tag = "1")]
    pub xds_matcher: ::core::option::Option<
        super::super::super::super::super::xds::r#type::matcher::v3::Matcher,
    >,
}
