// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct XRayConfig {
    #[prost(message, optional, tag = "1")]
    pub daemon_endpoint: ::core::option::Option<
        super::super::super::api::v2::core::SocketAddress,
    >,
    #[prost(string, tag = "2")]
    pub segment_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub sampling_rule_manifest: ::core::option::Option<
        super::super::super::api::v2::core::DataSource,
    >,
}
