// This file is @generated by prost-build.
pub mod envoy {
    pub mod extensions {
        pub mod filters {
            pub mod udp {
                pub mod udp_proxy {
                    pub mod session {
                        pub mod http_capsule {
                            pub mod v3 {
                                include!("envoy.extensions.filters.udp.udp_proxy.session.http_capsule.v3.rs");
                            }
                        }
                    }
                }
            }
        }
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
