// This file is @generated by prost-build.
pub mod envoy {
    pub mod config {
        pub mod filter {
            pub mod network {
                pub mod kafka_broker {
                    pub mod v2alpha1 {
                        include!("envoy.config.filter.network.kafka_broker.v2alpha1.rs");
                    }
                }
            }
        }
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
pub mod validate {
    include!("validate.rs");
}
