// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GrpcMethodList {
    #[prost(message, repeated, tag = "1")]
    pub services: ::prost::alloc::vec::Vec<grpc_method_list::Service>,
}
/// Nested message and enum types in `GrpcMethodList`.
pub mod grpc_method_list {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Service {
        #[prost(string, tag = "1")]
        pub name: ::prost::alloc::string::String,
        #[prost(string, repeated, tag = "2")]
        pub method_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    }
}
