// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DnsFilterConfig {
    #[prost(string, tag = "1")]
    pub stat_prefix: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub server_config: ::core::option::Option<dns_filter_config::ServerContextConfig>,
    #[prost(message, optional, tag = "3")]
    pub client_config: ::core::option::Option<dns_filter_config::ClientContextConfig>,
}
/// Nested message and enum types in `DnsFilterConfig`.
pub mod dns_filter_config {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct ServerContextConfig {
        #[prost(oneof = "server_context_config::ConfigSource", tags = "1, 2")]
        pub config_source: ::core::option::Option<server_context_config::ConfigSource>,
    }
    /// Nested message and enum types in `ServerContextConfig`.
    pub mod server_context_config {
        #[allow(clippy::derive_partial_eq_without_eq)]
        #[derive(Clone, PartialEq, ::prost::Oneof)]
        pub enum ConfigSource {
            #[prost(message, tag = "1")]
            InlineDnsTable(
                super::super::super::super::super::super::super::data::dns::v3::DnsTable,
            ),
            #[prost(message, tag = "2")]
            ExternalDnsTable(
                super::super::super::super::super::super::super::config::core::v3::DataSource,
            ),
        }
    }
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct ClientContextConfig {
        #[prost(message, optional, tag = "1")]
        pub resolver_timeout: ::core::option::Option<
            super::super::super::super::super::super::super::google::protobuf::Duration,
        >,
        #[deprecated]
        #[prost(message, repeated, tag = "2")]
        pub upstream_resolvers: ::prost::alloc::vec::Vec<
            super::super::super::super::super::super::config::core::v3::Address,
        >,
        #[deprecated]
        #[prost(message, optional, tag = "5")]
        pub dns_resolution_config: ::core::option::Option<
            super::super::super::super::super::super::config::core::v3::DnsResolutionConfig,
        >,
        #[prost(message, optional, tag = "4")]
        pub typed_dns_resolver_config: ::core::option::Option<
            super::super::super::super::super::super::config::core::v3::TypedExtensionConfig,
        >,
        #[prost(uint64, tag = "3")]
        pub max_pending_lookups: u64,
    }
}
