// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExtAuthz {
    #[prost(string, tag = "1")]
    pub stat_prefix: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub grpc_service: ::core::option::Option<
        super::super::super::super::super::config::core::v3::GrpcService,
    >,
    #[prost(bool, tag = "3")]
    pub failure_mode_allow: bool,
    #[prost(bool, tag = "4")]
    pub include_peer_certificate: bool,
    #[prost(
        enumeration = "super::super::super::super::super::config::core::v3::ApiVersion",
        tag = "5"
    )]
    pub transport_api_version: i32,
    #[prost(message, optional, tag = "6")]
    pub filter_enabled_metadata: ::core::option::Option<
        super::super::super::super::super::r#type::matcher::v3::MetadataMatcher,
    >,
    #[prost(string, tag = "7")]
    pub bootstrap_metadata_labels_key: ::prost::alloc::string::String,
    #[prost(bool, tag = "8")]
    pub include_tls_session: bool,
}
