// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct S2aConfiguration {
    #[prost(string, tag = "1")]
    pub s2a_address: ::prost::alloc::string::String,
}
