// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProfileActionConfig {
    #[prost(message, optional, tag = "1")]
    pub profile_duration: ::core::option::Option<
        super::super::super::super::super::google::protobuf::Duration,
    >,
    #[prost(string, tag = "2")]
    pub profile_path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub max_profiles: u64,
}
