// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileSystemHttpCacheConfig {
    #[prost(message, optional, tag = "1")]
    pub manager_config: ::core::option::Option<
        super::super::super::super::common::async_files::v3::AsyncFileManagerConfig,
    >,
    #[prost(string, tag = "2")]
    pub cache_path: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub max_cache_size_bytes: ::core::option::Option<
        super::super::super::super::super::super::google::protobuf::UInt64Value,
    >,
    #[prost(message, optional, tag = "4")]
    pub max_individual_cache_entry_size_bytes: ::core::option::Option<
        super::super::super::super::super::super::google::protobuf::UInt64Value,
    >,
    #[prost(message, optional, tag = "5")]
    pub max_cache_entry_count: ::core::option::Option<
        super::super::super::super::super::super::google::protobuf::UInt64Value,
    >,
    #[prost(uint32, tag = "6")]
    pub cache_subdivisions: u32,
    #[prost(float, tag = "7")]
    pub evict_fraction: f32,
    #[prost(message, optional, tag = "8")]
    pub max_eviction_period: ::core::option::Option<
        super::super::super::super::super::super::google::protobuf::Duration,
    >,
    #[prost(message, optional, tag = "9")]
    pub min_eviction_period: ::core::option::Option<
        super::super::super::super::super::super::google::protobuf::Duration,
    >,
    #[prost(bool, tag = "10")]
    pub create_cache_path: bool,
}
