// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Dependency {
    #[prost(enumeration = "dependency::DependencyType", tag = "1")]
    pub r#type: i32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
/// Nested message and enum types in `Dependency`.
pub mod dependency {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum DependencyType {
        Header = 0,
        FilterStateKey = 1,
        DynamicMetadata = 2,
    }
    impl DependencyType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                DependencyType::Header => "HEADER",
                DependencyType::FilterStateKey => "FILTER_STATE_KEY",
                DependencyType::DynamicMetadata => "DYNAMIC_METADATA",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "HEADER" => Some(Self::Header),
                "FILTER_STATE_KEY" => Some(Self::FilterStateKey),
                "DYNAMIC_METADATA" => Some(Self::DynamicMetadata),
                _ => None,
            }
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FilterDependencies {
    #[prost(message, repeated, tag = "1")]
    pub decode_required: ::prost::alloc::vec::Vec<Dependency>,
    #[prost(message, repeated, tag = "2")]
    pub decode_provided: ::prost::alloc::vec::Vec<Dependency>,
    #[prost(message, repeated, tag = "3")]
    pub encode_required: ::prost::alloc::vec::Vec<Dependency>,
    #[prost(message, repeated, tag = "4")]
    pub encode_provided: ::prost::alloc::vec::Vec<Dependency>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchingRequirements {
    #[prost(message, optional, tag = "1")]
    pub data_input_allow_list: ::core::option::Option<
        matching_requirements::DataInputAllowList,
    >,
}
/// Nested message and enum types in `MatchingRequirements`.
pub mod matching_requirements {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct DataInputAllowList {
        #[prost(string, repeated, tag = "1")]
        pub type_url: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    }
}
