// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Config {
    #[prost(bool, tag = "1")]
    pub upgrade_protobuf_to_grpc: bool,
    #[prost(bool, tag = "2")]
    pub ignore_query_parameters: bool,
}
