// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InternalListener {
    #[prost(message, optional, tag = "1")]
    pub buffer_size_kb: ::core::option::Option<
        super::super::super::super::super::google::protobuf::UInt32Value,
    >,
}
