// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MinimumClustersValidator {
    #[prost(uint32, tag = "1")]
    pub min_clusters_num: u32,
}
