// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AppleDnsResolverConfig {
    #[prost(bool, tag = "1")]
    pub include_unroutable_families: bool,
}
