// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CaresDnsResolverConfig {
    #[prost(message, repeated, tag = "1")]
    pub resolvers: ::prost::alloc::vec::Vec<
        super::super::super::super::super::config::core::v3::Address,
    >,
    #[prost(bool, tag = "3")]
    pub use_resolvers_as_fallback: bool,
    #[prost(bool, tag = "4")]
    pub filter_unroutable_families: bool,
    #[prost(message, optional, tag = "2")]
    pub dns_resolver_options: ::core::option::Option<
        super::super::super::super::super::config::core::v3::DnsResolverOptions,
    >,
    #[prost(message, optional, tag = "5")]
    pub udp_max_queries: ::core::option::Option<
        super::super::super::super::super::super::google::protobuf::UInt32Value,
    >,
}
