// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BasicAuth {
    #[prost(message, optional, tag = "1")]
    pub users: ::core::option::Option<
        super::super::super::super::super::config::core::v3::DataSource,
    >,
    #[prost(string, tag = "2")]
    pub forward_username_header: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BasicAuthPerRoute {
    #[prost(message, optional, tag = "1")]
    pub users: ::core::option::Option<
        super::super::super::super::super::config::core::v3::DataSource,
    >,
}
