// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FixedHeapConfig {
    #[prost(uint64, tag = "1")]
    pub max_heap_size_bytes: u64,
}
