// This file is @generated by prost-build.
pub mod envoy {
    pub mod config {
        pub mod transport_socket {
            pub mod raw_buffer {
                pub mod v2 {
                    include!("envoy.config.transport_socket.raw_buffer.v2.rs");
                }
            }
        }
    }
}
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
pub mod udpa {
    pub mod annotations {
        include!("udpa.annotations.rs");
    }
}
